apiVersion: apps/v1
kind: Deployment
metadata: 
    name: docker-k8-deploy.yaml
    labels: 
      app: docker-k8-demo
spec: 
    replicas: 1
    selector: 
      matchLabels:
        app: docker-k8-demo
    template: 
      metadata:
        labels: 
          app: docker-k8-demo
      spec: 
        containers: 
        - name: docker-k8-demo
          image: rajeshrayani/docker-demo:latest
          ports: 
          - containerPort: 8080
         
    