apiVersion: v1
kind: Service
metadata:
  name: docker-k8-service.yaml
spec:
  type: LoadBalancer
  selector:
    app: docker-k8-demo
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080